#!/bin/bash

# Copyright (c) 2010 Rob Myers <rob@robmyers.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

BOLLOCKS="\
affirmation|affirm|affirms|aporia|aporetic|appropriates|appropriation|\
archetypical|archetype|archetypes|autonomous|autonomy|\
baudrillardian|\
commodification|\
committed|commitment|convention|conventional|conventions|cunning|cunningly|\
death of the author|\
deconstruct|deconstruction|deconstructs|deleuzian|desire|desires|\
disrupt|disrupts|\
engage|engagement|engages|\
gaze|gender|\
identity|identity politics|\
intensifies|intensify|intensifying|interrogate|interrogates|interrogation|\
intertextual|intertextuality|\
juxtapose|juxtaposes|juxtaposition|\
lack|locus|\
matrix|mocking|mockingly|modalities|modality|myth|mythologies|mythology|myths|\
narrative|narrativisation|narrativization|narrativity|nexus|nodal|node|\
normative|normativity|notion|notions|\
objective|objectivity|objectivities|operate|operates|\
parody|parodic|parodies|plenitude|popular notions|practice|practise|\
problematic|problematics|\
reading|relation|relational|representation|representations|rhizome|\
situate|situated|situates|\
stereotype|stereotypes|strategy|strategies|\
subjective|subjectivity|subjectivities|subvert|subversion|subverts|\
text|textual|textuality|thinker|thinkers|trajectory|\
transgress|transgresses|transgression|transgressive|\
unfolding|undermine|undermining|undermines|\
work|works|wry|wryly|\
zizekian|zižekian"

if [ $# = 0 ]; then
 echo "usage: $(basename $0) <file> ..."
 exit 1
fi

egrep --line-number --ignore-case --color "\\b(${BOLLOCKS})\\b" $*

exit $?